### ISSUE TITLE
Erroe in ESP_32_BLE_Arduino

### ISSUE THREAD

**Issue by vvs551** [mhama/M5StackHIDCtrlAltDel#2]
In BLE Client:
error: too many arguments to function esp_err_t esp_ble_gattc_open

Latest version of arduino-esp32 and ESP32_BLE_Arduino

**Comment by mhama** [comment]
It looks like that your ESP32_BLE_Arduino is too new. Please use previous 6bad7b4 version. This is the specified version by arduino-esp32 as submodule.

see: https://github.com/espressif/arduino-esp32/tree/master/libraries

My arduino-esp32 on Documents\Arduino\hardware\espressif\esp32 is of commit-id 25dff4f and 
my ESP32_BLE_Arduino on Documents\Arduino\hardware\espressif\esp32\libraries\BLE is of commit-id 6bad7b4.

**Comment by mhama** [comment]
@vvs551 did you solve the problem?
I'll close this issue for now.
